swagger: '2.0'
info:
  title: Classic API Resource Documentation
  description: |
    Example API for demonstrating XSS payloads in Swagger.
  version: production
basePath: /
produces:
  - application/json
consumes:
  - application/json
security:
  - basicAuth: []
paths:
  /example:
    get:
      summary: Example endpoint with XSS payload
      operationId: exampleOperation
      tags:
        - example
      parameters:
        - name: id
          in: query
          required: true
          type: string
          description: |
            This parameter may be vulnerable to XSS:
            <script>alert('XSS')</script>
      responses:
        '200':
          description: Success
          schema:
            type: object
            properties:
              message:
                type: string
securityDefinitions:
  basicAuth:
    type: basic
